/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "authcheck.h"

bool_t
xdr_shttpd_conn (XDR *xdrs, shttpd_conn *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 15 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->global_passwd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->vhost))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->maxremoteuser))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->method))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->should_linger))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->status))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mime_flag))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->max_age))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->got_range))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->maxresponse))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->responselen))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->first_byte_index))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->last_byte_index))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->bytes_to_send))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->range_if))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->global_passwd);
		IXDR_PUT_LONG(buf, objp->vhost);
		IXDR_PUT_LONG(buf, objp->maxremoteuser);
		IXDR_PUT_LONG(buf, objp->method);
		IXDR_PUT_LONG(buf, objp->should_linger);
		IXDR_PUT_LONG(buf, objp->status);
		IXDR_PUT_LONG(buf, objp->mime_flag);
		IXDR_PUT_LONG(buf, objp->max_age);
		IXDR_PUT_LONG(buf, objp->got_range);
		IXDR_PUT_LONG(buf, objp->maxresponse);
		IXDR_PUT_LONG(buf, objp->responselen);
		IXDR_PUT_LONG(buf, objp->first_byte_index);
		IXDR_PUT_LONG(buf, objp->last_byte_index);
		IXDR_PUT_LONG(buf, objp->bytes_to_send);
		IXDR_PUT_LONG(buf, objp->range_if);
		}
		 if (!xdr_opaque (xdrs, objp->dirname, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->authorization, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->hostdir, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->remoteuser, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->encodedurl, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->useragent, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->charset, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->protocol, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->p3p, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->response, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->expnfilename, BUFFER_SIZE))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 15 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->global_passwd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->vhost))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->maxremoteuser))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->method))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->should_linger))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->status))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mime_flag))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->max_age))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->got_range))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->maxresponse))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->responselen))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->first_byte_index))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->last_byte_index))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->bytes_to_send))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->range_if))
				 return FALSE;

		} else {
		objp->global_passwd = IXDR_GET_LONG(buf);
		objp->vhost = IXDR_GET_LONG(buf);
		objp->maxremoteuser = IXDR_GET_LONG(buf);
		objp->method = IXDR_GET_LONG(buf);
		objp->should_linger = IXDR_GET_LONG(buf);
		objp->status = IXDR_GET_LONG(buf);
		objp->mime_flag = IXDR_GET_LONG(buf);
		objp->max_age = IXDR_GET_LONG(buf);
		objp->got_range = IXDR_GET_LONG(buf);
		objp->maxresponse = IXDR_GET_LONG(buf);
		objp->responselen = IXDR_GET_LONG(buf);
		objp->first_byte_index = IXDR_GET_LONG(buf);
		objp->last_byte_index = IXDR_GET_LONG(buf);
		objp->bytes_to_send = IXDR_GET_LONG(buf);
		objp->range_if = IXDR_GET_LONG(buf);
		}
		 if (!xdr_opaque (xdrs, objp->dirname, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->authorization, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->hostdir, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->remoteuser, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->encodedurl, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->useragent, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->charset, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->protocol, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->p3p, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->response, BUFFER_SIZE))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->expnfilename, BUFFER_SIZE))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->global_passwd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->vhost))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->maxremoteuser))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->method))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->should_linger))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mime_flag))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max_age))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->got_range))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->maxresponse))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->responselen))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->first_byte_index))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->last_byte_index))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->bytes_to_send))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->range_if))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->dirname, BUFFER_SIZE))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->authorization, BUFFER_SIZE))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->hostdir, BUFFER_SIZE))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->remoteuser, BUFFER_SIZE))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->encodedurl, BUFFER_SIZE))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->useragent, BUFFER_SIZE))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->charset, BUFFER_SIZE))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->protocol, BUFFER_SIZE))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->p3p, BUFFER_SIZE))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->response, BUFFER_SIZE))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->expnfilename, BUFFER_SIZE))
		 return FALSE;
	return TRUE;
}
