/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TWO_CALLS_H_RPCGEN
#define _TWO_CALLS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
	int b;
};
typedef struct numbers numbers;

struct strlist {
	int x;
	float balance;
	char *person;
	char *cellphone;
};
typedef struct strlist strlist;

#define ADD_PRINT_PROG 0x23451111
#define ADD_PRINT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  int * add_1(numbers *, CLIENT *);
extern  int * add_1_svc(numbers *, struct svc_req *);
#define printstr 2
extern  int * printstr_1(strlist *, CLIENT *);
extern  int * printstr_1_svc(strlist *, struct svc_req *);
extern int add_print_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  int * add_1();
extern  int * add_1_svc();
#define printstr 2
extern  int * printstr_1();
extern  int * printstr_1_svc();
extern int add_print_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);
extern  bool_t xdr_strlist (XDR *, strlist*);

#else /* K&R C */
extern bool_t xdr_numbers ();
extern bool_t xdr_strlist ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TWO_CALLS_H_RPCGEN */
