/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "two_calls.h"

bool_t
xdr_numbers (XDR *xdrs, numbers *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_strlist (XDR *xdrs, strlist *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->balance))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->person, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->cellphone, 200))
		 return FALSE;
	return TRUE;
}
